# Generated by Django 4.0.4 on 2022-05-12 12:59

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', ckeditor.fields.RichTextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('seo_desc', models.TextField(default='desc', max_length=50)),
                ('seo_keywords', models.TextField(default=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'))),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/')),
                ('desc', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(max_length=200)),
                ('twitter', models.URLField(max_length=250, null=True)),
                ('instagram', models.URLField(max_length=250, null=True)),
                ('facebook', models.URLField(max_length=250, null=True)),
                ('linkedin', models.URLField(max_length=250, null=True)),
                ('telegram', models.URLField(max_length=250, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.teamcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ishchilar',
            },
        ),
    ]
