# Generated by Django 4.0.4 on 2022-06-01 06:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectDesc_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectDesc_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectDesc_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectName_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectName_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ProjectName_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
